coverage-resource:
  git:
    username: 1582871549@qq.com
    password: 840742807du
    default-branch: master
    repository-path: D:\aaa
  maven:
    command: compile
    home-path: D:\Soft_Package\maven\apache-maven-3.5.3
  exec:
    default-name: dump.exec
    directory: exec




spring:
  datasource:
    first:
      username: root
      password: dujianwei
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    second:
      username: root
      password: dujianwei
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=UTC